### ISSUE TITLE
Fatal Error until you upload pictures

### ISSUE THREAD

**Issue by anybodesign** [Frosty-Media/ms-featured-image#4]
Hello :)
I notice that until you upload pictures, a Notice and a Fatal Error are displayed when you list the sites
and there is also unnecessary display on the setting page ("Array()" at the bottom of the setting box

**Comment by thefrosty** [comment]
@anybodesign can you supply which versions of PHP and WordPress you are running?

**Comment by anybodesign** [comment]
Yes, I run WP 4.9.8 and PHP 7.2.8 (local vm)

I understood the "Array()" thing, it appears when debug mode is set to true, which is my case.

**Comment by thefrosty** [comment]
I can't replicate any fatal errors.

Can you provide which type of Multisite your are running (subdomain vs subdirectory) and how many sites you've got. 

The Array output was an easy fix.

**Comment by anybodesign** [comment]
As I said, the error occured only the first time I activated the plugin, toot bad I did not copy/paste the error… Anyway I'm running basic multisite (subdirectory) with 2 sites
I'll try to replicate the error on a new install
thanks :)
